site_name: PTO Docs
site_description: PTO intrinsic and IR notes
docs_dir: docs
theme:
  name: material
nav:
  - 首页: README.md
  - TROWMAX 分析: intrin-intro.md
  - BinIntrinsic 设计: bin-intrinsic.md
  - PTO IR Manual: pto-ir-manual.md
